### ISSUE TITLE
SFW

### ISSUE THREAD

**Issue by whynot4335** [LuminesenceProject/LumiOS#19]
How are we supposed to play SFW games???

**Comment by whynot4335** [comment]
Nvm

**Comment by dvorme** [comment]
done 

![Image](https://github.com/user-attachments/assets/f8ffba19-bbab-4ead-8d79-c55bde1ff172)

Download it on Google Drive because it won't fit on Github either that or I'm too dumb to upload it 
https://drive.google.com/drive/folders/1TSKPTKpPOGYVonmk5nWloMBefWfbatZ3?usp=sharing
There's also a few other apps some of them are broken

**Comment by LuminesenceProject** [comment]
Cool
