### ISSUE TITLE
Modify

### ISSUE THREAD

**Issue by PolarizePcsOfficial** [LuminesenceProject/LumiOS#20]
I would like to be able to either modify the code or have you guys fix the proxy part of the OS because the proxy doesnt actually work but If Im able to modify it I may be able to create my own proxy that actually works or implement someone elses.

**Comment by LuminesenceProject** [comment]
I plan on making Lumi OS open source soon, so you will be free to modify and contribute to this repository whenever you want to, and open up a pull request to make the changes so I can approve them. But, right now its not open source since I'm currently working on an update. If you want, I can give you an older version that is _somewhat_ similar to the newest version, but you will have to adjust it soon for when the newest update comes out.
